
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://117.17.102.106/replay2?characterEncoding=utf-8
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver